export const DumbDatePickerClassLabels = {
    root: 'ddp-calendarContainer',
    header: 'ddp-calendarHead',
    browsers: 'ddp-calendarBrowsers',
    monthsBrowser: 'ddp-monthYearPicker',
    monthsContainer: 'ddp-monthsContainer',
    monthCell: 'ddp-monthYearCell',
    calendarBrowser: 'ddp-calendarPicker',
    calendarBody: 'ddp-calendarBody',
    calendarRow: 'ddp-calendarRow',
    calendarCell: 'ddp-calendarCell',
    dateBadge: 'ddp-dateBadge',
    isToday: 'ddp--isToday',
    isOutOfRange: 'ddp--isOutOfRange',
    weekNumber: 'ddp-weekNumber',
} as const;
